export const SET_KEY_TEST = 'SET_KEY_TEST'

export const USER_IS_LOGGED = 'USER_IS_LOGGED'

export const SET_BRIGHT_SYSTEM = 'SET_BRIGHT_SYSTEM'
export const SET_BRIGHT_SLIDER_BAR = 'SET_BRIGHT_SLIDER_BAR'

export const SET_DICE_RESULT = 'SET_DICE_RESULT'
export const SET_DICE_MAX = 'SET_DICE_MAX'
export const UPDATE_RESULTS_SECTIONS = 'UPDATE_RESULTS_SECTIONS'
export const SET_DISABLE_ROLL_BUTTON = 'SET_DISABLE_ROLL_BUTTON'

export const SET_WORD = 'SET_WORD'
export const SET_MAX_SIZE = 'SET_MAX_SIZE'
export const SET_MIN_SIZE = 'SET_MIN_SIZE'
export const SET_OPTION_MAX = 'SET_OPTION_MAX'
export const SET_OPTION_MIN = 'SET_OPTION_MIN'

export const LOG_IN_SENT = 'LOG_IN_SENT'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_IN_DEBUG = 'LOG_IN_DEBUG'
