export const USER_IS_LOGGED = 'USER_IS_LOGGED'

export const SET_BRIGHT_SYSTEM = 'SET_BRIGHT_SYSTEM'
export const SET_BRIGHT_SLIDER_BAR = 'SET_BRIGHT_SLIDER_BAR'

export const SET_DICE_RESULT = 'SET_DICE_RESULT'
export const SET_DICE_MAX = 'SET_DICE_MAX'
export const UPDATE_RESULTS_SECTIONS = 'UPDATE_RESULTS_SECTIONS'
export const DISABLE_ROLL_BUTTON = 'DISABLE_ROLL_BUTTON'